# .golangci.yml
linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocritic:
    enabled-checks:
      - argOrder
      - typeUnparen

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - gosec
      text: "G106: Expect directory permissions to be 0750 or less"
    - linters:
        - govet
      text: "composite literal uses unkeyed fields"

run:
  timeout: 5m
  skip-dirs:
    - vendor
